language: python

python: 3.7-dev
services: mongodb

env: 
 - DJANGO=2.2.1

before_install:
  - export DJANGO_SETTINGS_MODULE=public_python.settings  
  - export PIP_USE_MIRRORS=true
  - export PYTHONPATH="/usr/local/lib/python3.7/dist-packages"
  
install:
  - pip install -r requirements.txt
  - pip install django==$DJANGO --quiet
  - pip install psycopg2 --quiet
  - pip install codacy-coverage

script:
  - python manage.py compilemessages
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py test
  - coverage run --source='.' manage.py test root
  - coverage xml
  
after_success:
 - python-codacy-coverage -r coverage.xml
