# Generated by Django 2.1.7 on 2019-05-22 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NO_NAME', max_length=50)),
                ('email', models.CharField(default='NO_EMAIL', max_length=100)),
                ('message', models.TextField(default='NO_MESSAGE')),
            ],
        ),
    ]
