# Generated by Django 2.2.1 on 2019-05-22 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(default='NO_EMAIL', error_messages={'max_length': "Field 'email' is to long"}, max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(default='NO_NAME', error_messages={'max_length': "Field 'name' is to long"}, max_length=50),
        ),
    ]
