# Generated by Django 2.2.1 on 2019-05-29 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20190522_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(default='NO_EMAIL', error_messages={'blank': 'You need to fill your email', 'max_length': 'Your email is too long', 'null': 'You need to fill your email'}, max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(default='NO_MESSAGE', error_messages={'blank': 'You need to fill the message', 'null': 'You need to fill the message'}),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(default='NO_NAME', error_messages={'blank': 'You need to fill your name', 'max_length': 'Your name is too long', 'null': 'You need to fill your name'}, max_length=50),
        ),
    ]
