# Generated by Django 2.2.1 on 2019-05-29 12:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='ERROR', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='ERROR', max_length=255)),
                ('url', models.CharField(default='ERROR', max_length=255)),
                ('img', models.FileField(blank=True, null=True, upload_to='')),
                ('content', models.TextField(blank=True)),
                ('description', models.TextField(default='ERROR', max_length=511)),
                ('tags', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='NO_NAME', error_messages={'blank': 'You need to fill your name', 'max_length': 'Your name is too long', 'null': 'You need to fill your name'}, max_length=50)),
                ('email', models.TextField(default='NO_EMAIL', error_messages={'blank': 'You need to fill your email', 'max_length': 'Your email is too long', 'null': 'You need to fill your email'}, max_length=50)),
                ('content', models.TextField(default='NO_CONTENT', error_messages={'blank': 'You need to fill the comment', 'max_length': 'Your comment is too long', 'null': 'You need to fill the comment'}, max_length=255)),
                ('date', models.DateField(default=datetime.date.today)),
                ('post', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.Post')),
            ],
        ),
    ]
