# Generated by Django 2.1.7 on 2019-05-21 13:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who', models.CharField(default='ERROR', max_length=50)),
                ('position', models.CharField(default='ERROR', max_length=100)),
                ('description', models.TextField(default='ERROR')),
                ('rating', models.IntegerField(default=5, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('company', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='root.Company')),
            ],
        ),
    ]
