# Generated by Django 3.0.5 on 2020-10-05 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0002_company_page_skillcategory'),
        ('cover_letter', '0002_reference_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='attributes.Company'),
        ),
    ]
