# Generated by Django 2.1.7 on 2019-05-16 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobby',
            name='name',
            field=models.TextField(default='ERROR', max_length=30),
        ),
    ]
