# Generated by Django 2.1.7 on 2019-05-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_auto_20190516_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobby',
            name='name',
            field=models.CharField(default='ERROR', max_length=30),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(default='ERROR', max_length=50),
        ),
    ]
