# Generated by Django 2.1.7 on 2019-05-16 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_auto_20190516_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='progress',
            field=models.IntegerField(),
        ),
    ]
