# Generated by Django 2.1.7 on 2019-05-16 13:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0005_auto_20190516_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='progress',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
