# Generated by Django 2.1.7 on 2019-05-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0006_auto_20190516_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobby',
            name='icon',
            field=models.CharField(default='fa-file', max_length=20),
        ),
    ]
