# Generated by Django 2.1.7 on 2019-04-04 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0006_auto_20190324_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.TextField()),
                ('name', models.TextField()),
            ],
        ),
    ]
