# Generated by Django 2.1.7 on 2019-05-21 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0008_auto_20190517_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='root.Company'),
        ),
        migrations.AlterField(
            model_name='school',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='root.Company'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='root.SkillCategory'),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='SkillCategory',
        ),
    ]
