# Generated by Django 3.0.5 on 2020-10-05 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0002_company_page_skillcategory'),
        ('cv', '0009_auto_20190521_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='attributes.Company'),
        ),
        migrations.AlterField(
            model_name='school',
            name='direction',
            field=models.CharField(default='ERROR', max_length=50),
        ),
        migrations.AlterField(
            model_name='school',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='attributes.Company'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='attributes.SkillCategory'),
        ),
    ]
